# Generated by Django 5.2.1 on 2025-07-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coleccionista', '0001_initial'),
        ('Editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('anio_lanzamiento', models.IntegerField()),
                ('coleccionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coleccionista.coleccionista')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editorial.editorial')),
            ],
        ),
    ]
